language: php
php:
    - '5.6'
    - '7.1'

before_script:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --dev -v --prefer-source

script:
    - bin/phpspec run -fpretty --verbose
    #- bin/phpunit -c .
